version: '3.3'

services:
  db: #Container de MySQL
    image: mysql:5.7 # FROM myql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYQL_ROOT_PASSWORD: wordpress
      MYQL_DATABASE: wordpress
      MYQL_USER: marcelo
      MYSQL_PASSWORD: secret

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - "8000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: marcelo
      WORDPRESS_DB_PASSWORD: secret
      WORDPRESS_DB_NAME: wordpress
volumes:
  db_data: {}

